# Generated by Django 5.2.4 on 2025-08-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_questions_answer_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
