# Generated by Django 5.2.4 on 2025-08-21 02:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_client_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='city',
        ),
        migrations.RemoveField(
            model_name='client',
            name='paid',
        ),
        migrations.AddField(
            model_name='client',
            name='question',
            field=models.ManyToManyField(related_name='clients', to='customer.questions'),
        ),
        migrations.AddField(
            model_name='client',
            name='trials',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ClientQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('client', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.client')),
            ],
        ),
    ]
