# Generated by Django 5.2.4 on 2025-08-21 02:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_remove_client_city_remove_client_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientquestions',
            name='question_id',
            field=models.CharField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
