# Generated by Django 5.2.4 on 2025-08-21 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_clientquestions_question_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientquestions',
            name='question_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
