# Generated by Django 5.2.4 on 2025-08-21 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_alter_clientquestions_question_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answer_alphabet',
        ),
        migrations.AddField(
            model_name='answer',
            name='answer',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='clientquestions',
            name='question',
            field=models.ManyToManyField(blank=True, null=True, related_name='clientsquestion', to='customer.questions'),
        ),
        migrations.AlterField(
            model_name='client',
            name='question',
            field=models.ManyToManyField(blank=True, null=True, related_name='clients', to='customer.questions'),
        ),
    ]
