# Generated by Django 5.2.4 on 2025-08-21 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_remove_answer_answer_alphabet_answer_answer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='question',
        ),
        migrations.RemoveField(
            model_name='clientquestions',
            name='question',
        ),
        migrations.AlterField(
            model_name='clientquestions',
            name='client',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cq', to='customer.client'),
        ),
    ]
