# Generated by Django 5.2.4 on 2025-08-21 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_remove_client_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_verify',
            field=models.BooleanField(default=True),
        ),
    ]
